name: Bug Report
description: Report a bug or issue
title: "[Bug]: "
labels: ["bug"]
assignees:
  - NoahIsADeveloper
body:
  - type: textarea
    id: issue
    attributes:
      label: What happened?
      description: Tell us what broke, and how it broke.
      placeholder: Describe the issue, including any relevant error messages or behavior.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Tell us how we can recreate the issue.
      placeholder: |
        1. Open the game
        2. Write some code
        3. Game freezes
    validations:
      required: true
  - type: textarea
    id: modifications
    attributes:
      label: Client Modifications
      description: Tell us any modifications to the client you were using
      placeholder: Please state any clients or client modifications such as BloxStrap, any form of Exploits, Sober
    validations:
      required: true
  - type: checkboxes
    id: platform
    attributes:
      label: Platform
      options:
        - label: Computer
        - label: Phone
  - type: checkboxes
    id: agreement
    attributes:
      label: Submission
      options:
        - label: I have checked the latest release (https://github.com/NoahIsADeveloper/Substituted-Farmer/releases) to make sure my issue has not been fixed.
          required: true
        - label: I have searched the closed and open issues to make sure that this problem has not already been reported.
          required: true
        - label: I have stated any and all client modifications I may have used, such as BloxStrap, Exploits or Sober.
          required: true
